# @2021, bysrkh. Cirebon

# defines database migration
# supports only for PostgreSQL. Open for more vast SQL database support in the future
spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/user_boot
    default-schema: public
    user: postgres
    password: postgres
    change-log: classpath:db/db.changelog-master.xml

# defines database connection into local cluster
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_boot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# defines jpa properties
# supports logging for sql and only support with PostgreSQL
---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        format_sql: true

# define message resource bundles which is determined by running JVM application's classpath
# Reference: src/main/resources/i18n/messages*.properties
---
spring:
  messages:
    basename: i18n/messages

# defines tomcat port
server:
  port: 8081

# define the service is addressed as registered service to eureka instance
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8889/eureka'

# define the usage of spring load balancer instead of ribbon
---
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# defines logging
# define logback logging into console and rollover file by day and file size
# This config will override https://github.com/spring-projects/spring-boot/blob/v2.2.2.RELEASE/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/
# Reference: https://docs.spring.io/spring-boot/docs/2.2.2.RELEASE/reference/html/spring-boot-features.html#boot-features-logging
logging:
  file:
    max-size: 100KB
    total-size-cap: 100MB
    name: logs/user-boot.log
  pattern:
    rolling-file-name: 'logs/%d{yyyy/MMMM}/user-boot.%d{yyyy-MM-dd}.%i.log.gz'
    dateformat: yyyy-MM-dd HH:mm:ss.SSSZ
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG